/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202457201031;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Guru2 extends javax.swing.JPanel {

    /**
     * Creates new form Guru2
     */
    public Guru2() {
        initComponents();
        // Mengosongkan form input dan mengatur ulang komponen input
        reset();
        
        // Memuat data dari database ke dalam tabel guru pada GUI
        load_tabel_guru();
    }
    
    // Method untuk mereset (mengosongkan) form input
    void reset(){
        // Kosongkan field NIP
        tNIP.setText(null);
        
        // Aktifkan kembali agar NIP bisa diaedit 
        tNIP.setEditable(true);
        
        // Kosongkan field nama guru
        tNamaGuru.setText(null);
        
        // Reset pilihan jenis kelamin (combo box)
        cJenisKelamin.setSelectedItem(null);
        
        // Kosongkan field alamat
        tAlamat.setText(null);
    }
    
    // Method untuk memuat data dari tabel 'guru' ke dalam tabel GUI (tblGuru)
    void load_tabel_guru(){
        // Membuat model tabel baru
        DefaultTableModel model = new DefaultTableModel();
        
        // Menambahkan nama kolom ke dalam model tabel
        model.addColumn("NIP");
        model.addColumn("Nama Guru");
        model.addColumn("L/P");
        model.addColumn("Alamat");
        
        // SQL untuk mengambil semua data dari tabel guru
        String sql = "SELECT * FROM guru";
        
        try {
            // Membuat koneksi ke databse
            Connection conn = koneksi.konek();
            
            // Membuat statement SQL
            Statement st = conn.createStatement();
            
            // Menjalankan query dan menyimpan hasilnya
            ResultSet rs = st.executeQuery(sql);
            
            // Iterasi untuk setiap baris hasil query
            while (rs.next()){
                // Mengambil nilai dari masing - masing kolom
                String NIP = rs.getString("nip");
                String namaGuru = rs.getString("nama_guru");
                String jenisKelamin = rs.getString("gender");
                String alamat = rs.getString("alamat");
                
                // Menyusun data ke dalam array objek
                Object[]  baris = {NIP, namaGuru, jenisKelamin, alamat};
                
                // Menambah data ke model tabel
                model.addRow(baris);
        }    
        } catch (SQLException sQLException) {
            // Menampilkan pesan error jika terjadi gagal
            JOptionPane.showMessageDialog(null, "Gagal mengambil data");
        }
        
        // Menampilkan data model kedalam tabel GUI
        tblGuru.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCloseGuru2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuru = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tNIP = new javax.swing.JTextField();
        tNamaGuru = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tAlamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cJenisKelamin = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Guru");

        btnCloseGuru2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-cross-sign-20 (1).png"))); // NOI18N
        btnCloseGuru2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseGuru2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseGuru2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCloseGuru2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGuru);

        jLabel2.setText("NIP");

        tNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNIPActionPerformed(evt);
            }
        });

        tNamaGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaGuruActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Alamat");

        cJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));

        btnTambah.setBackground(new java.awt.Color(0, 153, 102));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-plus-24.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setBorder(null);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 102, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-change-24.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 51, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-remove-24.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 204, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-reset-24.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tAlamat)
                    .addComponent(cJenisKelamin, 0, 265, Short.MAX_VALUE)
                    .addComponent(tNIP)
                    .addComponent(tNamaGuru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNIPActionPerformed

    private void tNamaGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaGuruActionPerformed

    private void btnCloseGuru2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseGuru2MouseClicked
        // TODO add your handling code here:
        removeAll();
        revalidate();
        repaint();    
    }//GEN-LAST:event_btnCloseGuru2MouseClicked

    private void tblGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGuruMouseClicked
        // Mengambil indeks baris yang diklik oleh pengguna di tabel tblGuru
        int barisYangDipilih = tblGuru.rowAtPoint(evt.getPoint());
        
        // Mengambil nilai NIP dari kolom pertama (indeks 0)bpada baris yang dipilih
        String NIP = tblGuru.getValueAt(barisYangDipilih, 0).toString();
        
        // Mengambil nilai nama guru dari kolom kedua (indeks 1) pada baris yang dipilih
        String namaGuru = tblGuru.getValueAt(barisYangDipilih, 1).toString();
        
        // Mengambil nilai njenis kelamin dari kolom ketiga (indeks 2) pada baris yang dipilih
        String jenisKelamin = tblGuru.getValueAt(barisYangDipilih, 2).toString();
        
        // Mengambil nilai alamat dari kolom keempat (indeks 3) pada baris yang dipilih
        String alamat = tblGuru.getValueAt(barisYangDipilih, 3).toString();
        
        // Menampilkan nilai NIP ke dalam text field tNIP
        tNIP.setText(NIP);
        
        // Menonaktifkan field tNIP agar tidak bisa diedit (karena NIP bersifat unik dan tidak boleh diubah)
        tNIP.setEditable(false);
        
        // Menampilkan nama guru ke dalam text field tNamaGuru
        tNamaGuru.setText(namaGuru);
        
        // Menampilkan alamat ke dalam text field tAlamat
        tAlamat.setText(alamat);
        
        // Mengecek isi nilai jenis kelamin dan menyesuaikan pilihan pada combo box cJenisKelamin
        cJenisKelamin.setSelectedItem(jenisKelamin);          
    }//GEN-LAST:event_tblGuruMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // Mengambil input NIP dari text field tNIP
        String NIP = tNIP.getText();
        
        // Mengambil input nama guru dari text field tNamaGuru
        String namaGuru = tNamaGuru.getText();
        
        // Mengambil item yang dipilih dari combo box jenis kelamin
        String jenisKelamin = cJenisKelamin.getSelectedItem().toString();
        
        // Mengambil input alamat dari text field tAlamat
        String alamat = tAlamat.getText();
        
        // Mengubah nilai jenisKelamin dari label menjadi format singkatan yang disimpan di databse
        String jk = null;
        switch (jenisKelamin) {
            case "Laki - Laki":
                jk = "L";
                break;
            case "Perempuan":
                jk = "P";
                break;    
            default:
                jk = null;
                break;
        }
        
        // Menyusun perintah SQL untuk menyisipkan data guru ke dalam tabel guru
        String sql = "INSERT INTO guru(nip, nama_guru, gender, alamat) VALUES (?,?,?,?)";
        
        try {
            // Membuka koneksi ke databse menggunakan method konek()
            Connection conn = koneksi.konek();
            
            // Mempersiapkan query SQL dengan parameter (prepared statement)
            PreparedStatement ps = conn.prepareStatement(sql);
            
            // Mengisi parameeter pertama dengan NIP
            ps.setString(1, NIP);
            
            // Mengisi parameeter kedua dengan nama guru
            ps.setString(2, namaGuru);
            
            // Mengisi parameeter ketiga dengan jenis kelamin (L atau P)
            ps.setString(3, jk);
            
            // Mengisi parameeter keempat dengan alamat
            ps.setString(4, alamat);
            
            // Menjalankan perintah INSERT untuk menyimpan data ke database
            ps.execute();
            
            // Menampilkan perintah INSERT untuk menyimpan data ke database
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");   
        } catch (SQLException sQLException) {
            // Menampilkan pesan jika terjadi kesalahan saat menyimpan data
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        
        // Memuat ulang data guru di tabel tampilan
        load_tabel_guru();
        
        // Mereset semua input agar kosong kembali
        reset();  
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // Mengambil input NIP dari text field tNIP
        String NIP = tNIP.getText();
        
        // Mengambil input nama guru dari text field tNamaGuru
        String namaGuru = tNamaGuru.getText();
        
        // Mengambil item yang dipilih dari combo box jenis kelamin
        String jenisKelamin = cJenisKelamin.getSelectedItem().toString();
        
        // Mengambil input alamat dari text field tAlamat
        String alamat = tAlamat.getText();
        
        // Menyiapkan variabel untuk menyimpan singkantan jenis kelamin ("L" atau "P")
        String jk = null;
        
        // Mengubah label jenis kelamin menjadi singkatan yang sesuai dengan format database
        switch (jenisKelamin) {
            case "Laki - Laki":
                jk = "L";
                break;
            case "Perempuan":
                jk = "P";
                break;    
            default:
                jk = null;
                break;
        }
        
        // Menyusun perintah SQL untuk memperbarui data guru berdasarkan NIP 
        String sql = "UPDATE guru SET nama_guru=?, gender=?, alamat=?, WHERE nip=?";
        
        try {
            // Membuka koneksi ke databse
            Connection conn = koneksi.konek();
            
            // Mempersiapkan statement SQL dengan parameter (prepared statement)
            PreparedStatement ps = conn.prepareStatement(sql);
            
            // Mengisi parameter pertama (?) dengan nama guru
            ps.setString(1, namaGuru);
            
            // Mengisi parameter kedua (?) dengan njenis kelamin ("L"/"P")
            ps.setString(2, jk);
            
            // Mengisi parameter ketiga (?) dengan alamat
            ps.setString(3, alamat);
            
            // Mengisi parameter keempat (?) dengan NIP sebagai identitas data yang akan diubah
            ps.setString(4, NIP);
            
            // Menjalankan perintah UPDATE
            ps.execute();
            
            // Menampilkan pesan bahwa data berhasil diubah
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");   
        } catch (SQLException sQLException) {
            // Menampilkan pesan jika proses update gagal 
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        
        // Memuat ulang tabel guru untuk menampilkan data terbaru
        load_tabel_guru();
        
        // Mereset/mengosongkan form input
        reset();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // Mengambil nilai NIP text field tNIP
        String NIP = tNIP.getText();
        
        // Menyusun perintah SQL untuk menghapus data berdasarkan NIP
        String sql = "DELETE FROM guru WHERE nip=?";
        
        try {
            // Membuka koneksi ke database
            Connection conn = koneksi.konek();
            
            // Menyiapkan statement SQL dengan parameter (prepared statement)
            PreparedStatement ps = conn.prepareStatement(sql);
            
            // Mengisi parameter pertama (?) dengan nilai NIP
            ps.setString(1, NIP);
            
            // Menjalankan perintah DELETE untuk menghapus data dari database
            ps.execute();
            
            // Menampilkan pesan jika data berhasil dihapus
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");   
        } catch (SQLException sQLException) {
            // Menampilkan pesan jika terjadi kesalahan saat proses penghapusan
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        
        // Memuat ulang tabel guru untuk menampilkan data terbaru
        load_tabel_guru();
        
        // Mereset/mengosongkan form input
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCloseGuru2;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cJenisKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNIP;
    private javax.swing.JTextField tNamaGuru;
    private javax.swing.JTable tblGuru;
    // End of variables declaration//GEN-END:variables
}