/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202457201031;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Jurusan2 extends javax.swing.JPanel {

    /*
     * Panggil method dan load_tabel_jurusan dibawah ini tComponents,
     * agar ketika menu jurusan dibuka, data tabel muncul dan form inputan 
     * kosong.
     */ 
    public Jurusan2() {
        initComponents();
        reset();
        load_tabel_jurusan();
    }
    
    void reset(){
        // Kosongkan isi text field kode jurusan
        tKodejurusan.setText(null);
        
        // Aktifkan kembali text field kode kode jurusan agar bisa diedit
        tKodejurusan.setEditable(true);
        
        // Kosongkan isi text field nama jurusan
        tNamajurusan.setText(null);
    }
    
    void load_tabel_jurusan(){
        // Membuat objek model tabel baru
        DefaultTableModel model = new DefaultTableModel();
        
        // Menambah kolom kedalam model tabel
        
        // Kolom pertama untuk kode jurusan
        model.addColumn("Kode Jurusan");
        // Kolom kedua untuk nama jurusan
        model.addColumn("Nama Jurusan");
        
        // Query SQL untuk mengambil semua data dari tabel jurusan
        String sql = "SELECT * FROM jurusan";
        
        try {
            // Membuka koneksi ke database
            Connection conn = koneksi.konek();
            
            // Membuat statement untuk menjalankan query
            Statement st = conn.createStatement();
            
            // Menjalankan query dan menyimpan hasilnya dalam ResulSet
            ResultSet rs = st.executeQuery(sql);
            
            // Melakukan iterasi untuk setiap baris data hasil query
            while (rs.next()) {
                // Mengambil data kolom kode_jur
                String kodeJurusan = rs.getString("kode_jur");
                
                // Mengambil data kolom nama_jurusan
                String namaJurusan = rs.getString("nama_jurusan");
                
                // Membuat array berisi data satu baris
                Object[] baris = {kodeJurusan, namaJurusan};
                
                // Menambah array baris berisi ke dalam model tabel
                model.addRow(baris);
            }
        } catch (SQLException sQLException) {
            // Menampilkan pesan error jika gagal mengambil data dari database
            JOptionPane.showMessageDialog(null, "Gagal mengambil data");
        }
        
        // Menampilkan model yang sudah diisi ke dalam tabel GUI
        tblJurusan.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCloseJurusan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNamajurusan = new javax.swing.JTextField();
        tKodejurusan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJurusan = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Jurusan");

        btnCloseJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-cross-sign-20 (1).png"))); // NOI18N
        btnCloseJurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseJurusanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseJurusan)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCloseJurusan)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setText("Kode Jurusan");

        jLabel3.setText("Nama Jurusan");

        btnTambah.setBackground(new java.awt.Color(0, 153, 102));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-plus-24.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setBorder(null);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 102, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-change-24.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 51, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-remove-24.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 204, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201031/icons8-reset-24.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblJurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJurusanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJurusan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tKodejurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tNamajurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tNamajurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKodejurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseJurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseJurusanMouseClicked
        // TODO add your handling code here:
        removeAll();
        revalidate();
        repaint();
    }//GEN-LAST:event_btnCloseJurusanMouseClicked

    private void tblJurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJurusanMouseClicked
        // Ambil indeks baris yang diklik oleh pengguna di tabel tblJurusan
        int barisYangDipilih = tblJurusan.rowAtPoint(evt.getPoint());
        
        // Ambil nilai dari kolom pertama (indeks 0) pada baris yang dipilih, yaitu 'kode_jur'
        String kodeJurusan = tblJurusan.getValueAt(barisYangDipilih, 0).toString();
        
        // Ambil nilai dari kolom kedua (indeks 1) pada baris yang dipilih, yaitu 'nama_jurusan'
        String namaJurusan = tblJurusan.getValueAt(barisYangDipilih, 1).toString();
        
        // Tampilkan kode jurusan di text field tKodeJurusan
        tKodejurusan.setText(kodeJurusan);
        
        // Tampilkan pengeditan pada text field kode jurusan (agar tidak bisa diubah)
        tKodejurusan.setEditable(false);
        
        // Tampilkan nama jurusan di text field tNamaJurusan
        tNamajurusan.setText(namaJurusan);
    }//GEN-LAST:event_tblJurusanMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // Ambil input dari text field tKodeJurusan dan simpan ke dalam variabel kodeJurusan
        String kodeJurusan = tKodejurusan.getText();
        
        // Ambil input dari text field tNamaJurusan dan simpan ke variabel namaJurusan
        String namaJurusan = tNamajurusan.getText();
        
        // Query SQL untuk menyisipkan data ke tabel jurusan
        String sql = "INSERT INTO jurusan(kode_jur, nama_jurusan) VALUES(?,?)";
        
        try {
            // Buat koneksi ke database menggunakan method konek() dari class koneksi
            Connection conn = koneksi.konek();
            
            // Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);
            
            // Isi parameter pertama (?) dengan kode jurusan
            ps.setString(1, kodeJurusan);
            
            // Isi parameter kedua (?) dengan nama jurusan
            ps.setString(2, namaJurusan);
            
            // Jalankan query untuk menyimpan data ke database
            ps.execute();
            
            // Tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");   
        } catch (SQLException sQLException) {
            // Jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        
        // panggil method untuk memuat ulang data pada tabel jurusan
        load_tabel_jurusan();
        
        // Panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // Ambil input dari text field tKodeJurusan dan simpan ke variabel kodeJurusan
        String kodeJurusan = tKodejurusan.getText();
        
        // Ambil input dari text field tNamaJurusan dan simpan ke variabel namaJurusan
        String namaJurusan = tNamajurusan.getText();
        
        // Query SQL untuk mengubah data pada tabel jurusan
        String sql = "UPDATE jurusan SET nama_jurusan=? WHERE kode_jur=?";
        
        try {
            // Buat koneksi ke database menggunakan method konek() dari class koneksi
            Connection conn = koneksi.konek();
            
            // Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);
            
            // Isi parameter pertama (?) dengan kode jurusan
            ps.setString(1, kodeJurusan);
            
            // Isi parameter kedua (?) dengan nama jurusan
            ps.setString(2, namaJurusan);
            
            // jalankan query untuk menyimpan data ke database
            ps.execute();
            
            // Tampilkan pesan bahwa data berhasil diubah
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");   
        } catch (SQLException sQLException) {
            // Jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        
        // Panggil method untuk memuat ulang data pada tabel jurusan
        load_tabel_jurusan();
        
        // panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // Ambil input dari text field tKodeJurusan dan simpan ke variabel kodeJurusan
        String kodeJurusan = tKodejurusan.getText();
        
        // Query SQL untuk data pada tabel jurusan berdasarkan kode_jur
        String sql = "DELETE FROM jurusan WHERE kode_jur=?";
        
        try {
            // Buat koneksi ke database menggunakan method konek() dari class koneksi
            Connection conn = koneksi.konek();
            
            // Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);
        
            // Isi parameter pertama (?) dengan kode jurusan
            ps.setString(1, kodeJurusan);
            
            // Jalankan query untuk menyimpan data ke database
            ps.execute();
            
            // Tanpilkan pesan bahwa data berhasil dihapus
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");   
        } catch (SQLException sQLException) {
            // Jika terjadi kesalahan saat mengahapus data, tampilkan pesan gagal 
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        
        // Panggil method untuk memuat ulang data pada tabel jurusan
        load_tabel_jurusan();
        
        // Panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCloseJurusan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tKodejurusan;
    private javax.swing.JTextField tNamajurusan;
    private javax.swing.JTable tblJurusan;
    // End of variables declaration//GEN-END:variables
}
